<!DOCTYPE html>
<html>
<head>
    <title>This Email generated by www.codechief.org</title>
</head>
<body>
    <h1>Hello, {{ $customer['name'] }}</h1>
    <p>This is the Quotation for our services.</p>
    <p>We just keep your details for quotation.</p>
    <p>Email: {{ $customer['email'] }}</p>
    <p>Address: {{ $customer['address'] }}</p>

        <table class="table table-bordered table-responsive-lg">
        <tr>
            <th>Qty</th>
            <th>Name</th>
            <th>description</th>
            <th>Price</th>
        </tr>
        @foreach ($customer['products'] as $product)
            <tr>
                <td>{{ $product->qty }}</td>
                <td>{{ $product->name }}</td>
                <td>{{ $product->description }}</td>
                <td>{{ $product->price }}</td>
            </tr>
        @endforeach
        <tr></tr>
        <tr>
            <td><strong>Total:</strong></td>
            <td>{{ $customer['quotation'] }}</td>
        </tr>
    </table>

    <p>Thank you</p>
</body>
</html>